quarkus.datasource.db-kind=${DB_KIND:mysql}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:none}
quarkus.datasource.jdbc.url=${DB_JDBC_URL:none}
quarkus.hibernate-orm.schema-management.strategy = validate

firebase.service-account=${FIREBASE_SERVICE_ACCOUNT_LOCATION:none}
app.name=${APP_NAME:none}
app.version=${APP_VERSION:dev}

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=leote
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=no-file
%test.firebase.service-account-location=none

quarkus.hibernate-orm.log.sql = true
quarkus.hibernate-orm.log.format-sql = true
quarkus.hibernate-orm.log.bind-parameters = false

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.access-control-allow-credentials=true
